<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useApi } from '../composables/useApi'
import { useTheme } from '../composables/useTheme'
import type { StoredImage, GameState, Breadcrumb } from '../types'
import Breadcrumbs from '../components/Breadcrumbs.vue'
import SkeletonLoader from '../components/SkeletonLoader.vue'

const route = useRoute()
const { getImage, getGame, loading } = useApi()
const { setSession } = useTheme()

const image = ref<StoredImage | null>(null)
const gameState = ref<GameState | null>(null)

const imageId = computed(() => route.params.imageId as string)

const fileSizeKb = computed(() => {
  if (!image.value) return '?'
  return (image.value.fileSize / 1024).toFixed(1)
})

const breadcrumbs = computed<Breadcrumb[]>(() => {
  if (!image.value) return []
  return [
    { label: 'Games', href: '/' },
    { label: gameState.value?.game.name || 'Loading...', href: `/games/${image.value.gameId}` },
    { label: image.value.label || 'Image' },
  ]
})

onMounted(async () => {
  image.value = await getImage(imageId.value)
  if (image.value) {
    setSession(image.value.gameId)
    gameState.value = await getGame(image.value.gameId)
  }
})
</script>

<template>
  <!-- Loading State -->
  <div v-if="loading" class="image-loading">
    <SkeletonLoader variant="text" width="200px" />
    <SkeletonLoader variant="title" width="200px" />
    <SkeletonLoader variant="image" height="400px" />
    <SkeletonLoader variant="card" class="mt-4" />
  </div>

  <!-- Content -->
  <div v-else-if="image" class="animate-fade-in">
    <Breadcrumbs :items="breadcrumbs" />
    <h2>{{ image.label || 'Image' }}</h2>

    <img
      :src="`/images/${image.id}/file`"
      :alt="image.label || 'Image'"
      class="full-image"
    />

    <div class="card mt-20">
      <h3>Details</h3>
      <div class="stat">
        <span class="stat-label">Type</span>
        <span>{{ image.entityType }}</span>
      </div>
      <div class="stat">
        <span class="stat-label">Dimensions</span>
        <span>{{ image.width || '?' }} x {{ image.height || '?' }}</span>
      </div>
      <div class="stat">
        <span class="stat-label">Size</span>
        <span>{{ fileSizeKb }} KB</span>
      </div>
      <div class="stat">
        <span class="stat-label">Format</span>
        <span>{{ image.mimeType }}</span>
      </div>
      <div v-if="image.description" class="stat">
        <span class="stat-label">Description</span>
        <span>{{ image.description }}</span>
      </div>
      <div v-if="image.generationTool" class="stat">
        <span class="stat-label">Generated by</span>
        <span>{{ image.generationTool }}</span>
      </div>
    </div>

    <div v-if="image.generationPrompt" class="card">
      <h3>Generation Prompt</h3>
      <p>{{ image.generationPrompt }}</p>
    </div>

    <p class="mt-20">
      <router-link :to="`/${image.entityType}s/${image.entityId}`" class="btn">
        View {{ image.entityType }}
      </router-link>
    </p>
  </div>
  <p v-else class="empty">Image not found.</p>
</template>

<style scoped>
.full-image {
  max-width: 100%;
  border-radius: 8px;
}
</style>
